apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: risk-analysis-service
  description: "Serviço de análise de risco para operações de investimento e produtos financeiros"
  annotations:
    backstage.io/api-docs-ref: file: ./openapi.yaml
spec:
  type: service
  lifecycle: production
  owner: group:produtos-financeiros
  system: system:wealth-manager
